### ISSUE TITLE
Busca de professor pode retornar aluno

### ISSUE THREAD

**Issue by pmdpaula** [danielbergholz/teach-other#1]
No arquivo [[id].tsx (45)](https://github.com/danielbergholz/teach-other/blob/c9b1ab4658ffc74560e4676d80bf4b5016f35e70/pages/api/teacher/%5Bid%5D.tsx#L45) o retorno pode ser um aluno ao invés de professor.
Fiz dessa forma para ajustar.
.findOne({ _id: new ObjectId(id), teacher: true });

**Comment by danielbergholz** [comment]
Caramba, não sei como eu deixei essa passar, vou ajustar agora mesmo.
Muito Obrigado!

**Comment by danielbergholz** [comment]
Caramba, não sei como eu deixei essa passar, vou ajustar agora mesmo.
Muito Obrigado!
